# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_input.setObjectName("ip_input")
        self.horizontalLayout.addWidget(self.ip_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.port_input = QtWidgets.QLineEdit(self.centralwidget)
        self.port_input.setObjectName("port_input")
        self.horizontalLayout_2.addWidget(self.port_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setObjectName("username_input")
        self.horizontalLayout_3.addWidget(self.username_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout_4.addWidget(self.password_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_5.addWidget(self.login_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 127, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pasvRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.pasvRadioButton.setObjectName("pasvRadioButton")
        self.horizontalLayout_6.addWidget(self.pasvRadioButton)
        self.portRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.portRadioButton.setObjectName("portRadioButton")
        self.horizontalLayout_6.addWidget(self.portRadioButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.local_directory = QtWidgets.QLabel(self.centralwidget)
        self.local_directory.setObjectName("local_directory")
        self.verticalLayout.addWidget(self.local_directory)
        self.local_files = QtWidgets.QListWidget(self.centralwidget)
        self.local_files.setObjectName("local_files")
        self.verticalLayout.addWidget(self.local_files)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.new_local_folder_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_local_folder_name.sizePolicy().hasHeightForWidth())
        self.new_local_folder_name.setSizePolicy(sizePolicy)
        self.new_local_folder_name.setObjectName("new_local_folder_name")
        self.verticalLayout_4.addWidget(self.new_local_folder_name)
        self.new_local_folder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_local_folder.sizePolicy().hasHeightForWidth())
        self.new_local_folder.setSizePolicy(sizePolicy)
        self.new_local_folder.setObjectName("new_local_folder")
        self.verticalLayout_4.addWidget(self.new_local_folder)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.remote_directory = QtWidgets.QLabel(self.centralwidget)
        self.remote_directory.setObjectName("remote_directory")
        self.verticalLayout_2.addWidget(self.remote_directory)
        self.remote_files = QtWidgets.QListWidget(self.centralwidget)
        self.remote_files.setObjectName("remote_files")
        self.verticalLayout_2.addWidget(self.remote_files)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.new_remote_folder_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_remote_folder_name.sizePolicy().hasHeightForWidth())
        self.new_remote_folder_name.setSizePolicy(sizePolicy)
        self.new_remote_folder_name.setObjectName("new_remote_folder_name")
        self.verticalLayout_5.addWidget(self.new_remote_folder_name)
        self.new_remote_folder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_remote_folder.sizePolicy().hasHeightForWidth())
        self.new_remote_folder.setSizePolicy(sizePolicy)
        self.new_remote_folder.setObjectName("new_remote_folder")
        self.verticalLayout_5.addWidget(self.new_remote_folder)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.text_display = QtWidgets.QTextEdit(self.centralwidget)
        self.text_display.setReadOnly(True)
        self.text_display.setObjectName("text_display")
        self.verticalLayout_3.addWidget(self.text_display)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client"))
        self.label.setText(_translate("MainWindow", "ip"))
        self.label_2.setText(_translate("MainWindow", "port"))
        self.label_3.setText(_translate("MainWindow", "username"))
        self.label_4.setText(_translate("MainWindow", "password"))
        self.login_button.setText(_translate("MainWindow", "login"))
        self.pasvRadioButton.setText(_translate("MainWindow", "pasv"))
        self.portRadioButton.setText(_translate("MainWindow", "port"))
        self.label_6.setText(_translate("MainWindow", "local directory"))
        self.local_directory.setText(_translate("MainWindow", "."))
        self.new_local_folder.setText(_translate("MainWindow", "new folder"))
        self.label_8.setText(_translate("MainWindow", "remote directory"))
        self.remote_directory.setText(_translate("MainWindow", "."))
        self.new_remote_folder.setText(_translate("MainWindow", "new folder"))

