# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        MainWindow.setMaximumSize(QtCore.QSize(1025, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 141, 21))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 127, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pasvRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.pasvRadioButton.setObjectName("pasvRadioButton")
        self.horizontalLayout_6.addWidget(self.pasvRadioButton)
        self.portRadioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.portRadioButton.setObjectName("portRadioButton")
        self.horizontalLayout_6.addWidget(self.portRadioButton)
        self.text_display = QtWidgets.QTextEdit(self.centralwidget)
        self.text_display.setGeometry(QtCore.QRect(0, 311, 1021, 261))
        self.text_display.setReadOnly(True)
        self.text_display.setObjectName("text_display")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 0, 1019, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ip_input.setObjectName("ip_input")
        self.horizontalLayout.addWidget(self.ip_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.port_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.port_input.setObjectName("port_input")
        self.horizontalLayout_2.addWidget(self.port_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.username_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.username_input.setObjectName("username_input")
        self.horizontalLayout_3.addWidget(self.username_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.password_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout_4.addWidget(self.password_input)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.login_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_5.addWidget(self.login_button)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 60, 1011, 242))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.local_directory = QtWidgets.QLabel(self.layoutWidget2)
        self.local_directory.setObjectName("local_directory")
        self.verticalLayout.addWidget(self.local_directory)
        self.local_files = QtWidgets.QListWidget(self.layoutWidget2)
        self.local_files.setObjectName("local_files")
        self.verticalLayout.addWidget(self.local_files)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.upload_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.upload_button.setObjectName("upload_button")
        self.horizontalLayout_7.addWidget(self.upload_button)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.remote_directory = QtWidgets.QLabel(self.layoutWidget2)
        self.remote_directory.setObjectName("remote_directory")
        self.verticalLayout_2.addWidget(self.remote_directory)
        self.remote_files = QtWidgets.QListWidget(self.layoutWidget2)
        self.remote_files.setObjectName("remote_files")
        self.verticalLayout_2.addWidget(self.remote_files)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.download_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_8.addWidget(self.download_button)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client"))
        self.pasvRadioButton.setText(_translate("MainWindow", "pasv"))
        self.portRadioButton.setText(_translate("MainWindow", "port"))
        self.label.setText(_translate("MainWindow", "ip"))
        self.label_2.setText(_translate("MainWindow", "port"))
        self.label_3.setText(_translate("MainWindow", "username"))
        self.label_4.setText(_translate("MainWindow", "password"))
        self.login_button.setText(_translate("MainWindow", "login"))
        self.label_6.setText(_translate("MainWindow", "local directory"))
        self.local_directory.setText(_translate("MainWindow", "."))
        self.upload_button.setText(_translate("MainWindow", "upload"))
        self.label_8.setText(_translate("MainWindow", "remote directory"))
        self.remote_directory.setText(_translate("MainWindow", "."))
        self.download_button.setText(_translate("MainWindow", "download"))

